SciML/ExponentialUtilities.jl

src/arnoldi.jl, src/krylov_phiv.jl, test/runtests.jl
This discards any imaginary parts of the dot products, which should be
zero to within machine precision.
=> Support explicitly real Gram-Schmidt coefficients for Hermitian matrices

src/krylov_phiv.jl
This enables the use of Lanczos iteration for e.g. skew-Hermitian matrices by multiplying the operator by `im` when performing the Krylov iteration (thus yielding a Hermitian operator) and then taking a complex time-step.
=> Diagonalize before multiplying by time-step in the case of Hermitian operators

src/ExponentialUtilities.jl, src/arnoldi.jl, src/krylov_expv.jl, src/krylov_phiv.jl, src/krylov_phiv_adaptive.jl, src/stegr_cache.jl, test/runtests.jl
As discussed in #1, I've implemented an alternative interface to `exvp!` for the Hermitian case, where the Krylov subspace is successively built up, but the iteration is terminated, if a stopping criterion based on an exponentiation error estimate is fulfilled. For time-stepping, where the error of the exponentiation, and not the condition number of the Krylov subspace, is important, I have found this to be a more reliable indicator of when to terminate the iteration.
- This PR follows #5, but does not really depend on it, so before this is merged, it should be rebased on whatever state master is in at that time.
- The Krylov iterations previously used a separate `cache` vector, which I skipped. Instead I use the "next" vector in the subspace, i.e. `V[:,j+1]`, where `cache` after being …
=> Alternative interface to expv!

src/arnoldi.jl, src/krylov_expv.jl, test/runtests.jl
- Added back `cache` kwarg for now, as requested in JuliaDiffEq/OrdinaryDiffEq.jl#517.
- Remove a few unused arguments to the `*_step!` methods
- Fixed indentation of tests
=> Minor things

src/krylov_phiv_adaptive.jl
I have found that for time-adaptive methods like `phiv_timestep` in `ExponentialUtilities.jl`, `eltype(A)` for an operator `A` should be also defined. Isn't it sufficient to use `eltype(b)` in the code instead, as each element of the corresponding matrix `U` (lin comb of $t^p \varphi(tA)$) will have the element type of `b`?
Here's a MWE:
```julia
struct TransitionModel
A
end
LinearAlgebra.size(m::TransitionModel, i::Int64) = size(m.A, i)
LinearAlgebra.ishermitian(m::TransitionModel) = ishermitian(m.A)
LinearAlgebra.mul!(y, m::TransitionModel, b) = mul!(y, m.A, b)
function LinearAlgebra.mul!(Y, m::TransitionModel, B::AbstractMatrix{T}) where {T} 
N = size(A,1)
for j in 1:(N+1)
y = Y[:,j]
mul!(y, m, B[:,j])
Y[:,j] = y
end    
end
LinearAlgebra.opnorm(m::TransitionModel, p) = opnorm(m.A, p) …
```
=> Use eltype of `b` rather than `A` in adaptive methods

README.md, src/ExponentialUtilities.jl, src/StegrWork.jl, src/arnoldi.jl, src/krylov_phiv.jl, src/krylov_phiv_adaptive.jl, src/krylov_phiv_error_estimate.jl, src/phi.jl, src/stegr_cache.jl, src/utils.jl
Two main jobs to do:
Note that I've refactored `expv` into two functions, depending on the choice of `mode`. This is because the code for the two stopping modes are vastly different and they use different keyword arguments.
=> ExponentialUtilities v1.3

src/ExponentialUtilities.jl, src/StegrWork.jl, src/exp.jl, src/krylov_phiv.jl, src/krylov_phiv_error_estimate.jl, src/phi.jl, test/runtests.jl
I have translated the `exp!` function in `LinearAlgebra` to a non-allocating version (temporarily named `_exp!`). The next step is to replace the `exp!` occurrences in the package to `_exp!` and then remove the former.
In cases where the matrices for which `exp!` is called are small (i.e. small number of Krylov iterations) I suspect there won't be too much improvement (though adding them up can still probably save some noticeable time). The improvement should be more visible for larger Krylov subspaces.
=> WIP: Non-allocating `exp!`

README.md, src/exp.jl, test/runtests.jl
Currently, `exp_generic` needs [this PR](https://github.com/JuliaLang/julia/pull/34008) to work properly on `Number` types so I updated it to not use `UniformScaling` objects if `x` is a number. 
I also added `exp_generic` to the README and added some number tests.
=> Add `exp_generic` to README and make it work with `Number`s. 

src/exp.jl
> For IEEE double precision arithmetic the best choice of degree of Padé approximant turns
out to be 13, rather than the 6 or 8 used by previous authors.
From the abstract of
HIGHAM, N. J. (2005). "THE SCALING AND SQUARING METHOD FOR THE MATRIX EXPONENTIAL REVISITED." SIAM J. MATRIX ANAL. APPL.Vol. 26, No. 4, pp. 1179–1193
=> Default to type 13,13 Padé approximantion

src/arnoldi.jl, src/krylov_phiv.jl, src/krylov_phiv_error_estimate.jl
I generalized some definitions to support CUDA, which closes #27 . but to make `expv!` work on CUDA, one needs this patch: 
https://github.com/JuliaGPU/CUDA.jl/pull/217
and this function
```jl
function ExponentialUtilities.expv!(w::CuVector{Tw}, t::Real, Ks::KrylovSubspace{T, U};
cache=nothing, dexpHe::CuVector = CuVector{U}(undef, Ks.m)) where {Tw, T, U}
m, beta, V, H = Ks.m, Ks.beta, getV(Ks), getH(Ks)
@assert length(w) == size(V, 1) "Dimension mismatch"
if cache == nothing
cache = Matrix{U}(undef, m, m)
elseif isa(cache, ExpvCache)
cache = get_cache(cache, m)
else
throw(ArgumentError("Cache must be an ExpvCache"))
end
copyto!(cache, @view(H[1:m, :]))
if ishermitian(cache)
F = eigen!(SymTridiagonal(cache))
expHe = F.vectors * (exp.(lmul!(t,F.values)) .* @view(F.vectors[1, :]))
else …
```
=> generalize function definitions to support cuda

src/arnoldi.jl, src/krylov_phiv.jl, src/krylov_phiv_error_estimate.jl, test/runtests.jl
If the RHS is zero, terminate the Krylov iterations directly, before dividing by `β`, which would yield a subspace filled with `NaNs`. I did not add a test for the augmented version, because I don't know how it works.
I also added a `real()` around the cache for the Lanczos case, but I don't remember when this was necessary. I'll see if I can come up with a case.
=> Zero fixes

src/exp.jl, test/runtests.jl
This is useful when using the function inside an optimization where the step should simply be handled and thrown away.
=> Avoid throwing on Infs in exp_generic

src/exp.jl
Reuses memory to cut down on allocations and keep the memory hotter in the cache (depending on size of the arrays).
=> Faster exp_pade_p(::Matrix, ::Val{13}, ::Val{13})

Project.toml, src/exp.jl, test/runtests.jl
Fixing a couple oversights and adding tests to make sure `StaticArrays.MMatrix` still works, as an example generic mutable AbstractArray.
Those oversights were:
1. `Base.Experimental.Const` is only defined for `Array`.
2. `lu!` is only defined for `StridedMatrix`. `MMatrix` doesn't subtype strided, and also does not return `LinearAlgebra.LU`, returning `StaticArrays.LU` instead. The latter doesn't support `rdiv!`.
While it'd be nice to fix "2." in `StaticArrays`, for now it's easiest to just work around it here.
=> Fix exp_generic for general AbstractMatrix.

src/exp.jl
I ran into a `trunc` error because `x` was too large.
Maybe I shouldn't microoptimize the intlog2 call, since it's pretty fast in the first place, but for now...
=> Make faster `intlog2` use fallback in case arg is out of range.

src/exp.jl, test/runtests.jl
For huge duals, we probably don't want to unroll much at all.
For small duals, unrolling more helps.
The intention is to try and keep up with `SMatrix` performance, but while this does well in microbenchmarks, in practice it is still several times slower in the real workload, with 80% GC time vs 15% GC time for the SMatrix version. =/
=> Unroll based off of sizeof(eltype(C))

src/exp_generic.jl, test/runtests.jl
See the added test for an example.
=> Avoid integer overflow when scaling the argument in the generic exp

src/ExponentialUtilities.jl
The method `ExpMethodGeneric` was not exported, instead `ExpMethodHighamGeneric` got exported but in the package, the generic exp method struct is called `ExpMethodGeneric`
https://github.com/SciML/ExponentialUtilities.jl/blob/f34954f875d0c02ce04ea868601d381323c32a06/src/exp_generic.jl#L112-L114
`ExpMethodHighamGeneric` was only mentioned once in the export list:
https://github.com/SciML/ExponentialUtilities.jl/search?q=ExpMethodHighamGeneric
=> likely a typo in export

Project.toml, src/StegrWork.jl
Closes #76.
Apparently `libblastrampoline_jll` works on 1.6??
cc @viralbshah
=> update liblapack location to use libblastrampoline_jll if available

Project.toml, src/ExponentialUtilities.jl, src/exp_baseexp.jl, src/exp_noalloc.jl
Fixes https://github.com/SciML/ExponentialUtilities.jl/issues/81
=> add Balance fallback via GenericSchur for non-BlasFloat

.gitignore, src/ExponentialUtilities.jl, src/arnoldi.jl, src/krylov_phiv.jl
This PR will make time evolution in CuYao (the CUDA version of Yao, https://github.com/QuantumBFS/CuYao.jl) work properly.
=> Support CUDA arrays

Project.toml, src/ExponentialUtilities.jl, src/krylov_phiv.jl, src/krylov_phiv_adaptive.jl, test/gpu/gputests.jl
Hello,
by changing only the syntax of several lines I implemented the GPU support for the `expv` and `expv_timestep` functions. The following code works now
```julia
using LinearAlgebra
using SparseArrays
using ExponentialUtilities
using BenchmarkTools
using CUDA
using CUDA.CUSPARSE
CUDA.allowscalar(false)
##
n = 70000
A = sprand(ComplexF64, n, n, 10 / n)
A = triu(A, 1) + sprand(ComplexF64, n, n, 1 / n)
b = rand(ComplexF64, n)
t = 0.1
ts = Array(LinRange(0, 1, 300))
expv(t, A, b)
@btime expv_timestep(ts, A, b)
A = CuSparseMatrixCSR(A)
b = CuArray(b)
expv(t, A, b)
@btime expv_timestep(ts, A, b)
```
=> GPU support for expv and expv_timestep

src/StegrWork.jl, test/basictests.jl
Currently, the vl/vu for the eigen value calculation for Hermitian case with error_estimation mode are `Real` type and can cause a runtime dispatch. Since they refer to the lower & upper limits to the eigen-values to calculate, it would make sense for them to just be the same type as the eltype of eigenvalues array `w`
https://github.com/SciML/ExponentialUtilities.jl/blob/0200288b7143535ae41580b342a54f31ea52279a/src/StegrWork.jl#L22
and they are converted as such in the ccalls as `Ref{elty}` with elty = Float32/64
https://github.com/SciML/ExponentialUtilities.jl/blob/0200288b7143535ae41580b342a54f31ea52279a/src/StegrWork.jl#L38
In addition, for the algorithm here, all eigenvalues are calculated (range='A' for all)
https://github.com/SciML/ExponentialUtilities.jl/blob/0200288b7143535ae41580 …
=> vl/u type: Real to concrete to avoid runtime dispatch

Project.toml, src/ExponentialUtilities.jl, src/precompile.jl
This pull request migrates the package from [SnoopPrecompile](https://github.com/timholy/SnoopCompile.jl/tree/master/SnoopPrecompile) to [PrecompileTools](https://github.com/JuliaLang/PrecompileTools.jl).
PrecompileTools is **nearly a drop-in replacement** except that there are **changes in naming and how developers locally disable precompilation** (to make their development workflow more efficient). These changes are described in [PrecompileTool's enhanced documentation](https://julialang.github.io/PrecompileTools.jl/stable/), which also includes instructions for users on how to set up custom "Startup" packages, handling precompilation tasks that are not amenable to workloads, and tips for troubleshooting.
Why the new package? It meets several goals:
- The name "SnoopPrecompile" was …
=> Migrate from SnoopPrecompile to PrecompileTools

src/exp_generic.jl, test/basictests.jl
This would fix https://github.com/SciML/ExponentialUtilities.jl/issues/132, but the result is always dense so I'm not sure using a sparse matrix is actually a good idea because the result is dense. However, you do get some sparse LU so maybe it works out for somebody?
=> Allow for sparse matrices in exponential!?

src/krylov_phiv_adaptive.jl
The documentation for the `expv_timestep` method contained a typo: `exp_timestep`.
=> Fix typo in expv_timestep documentation

src/arnoldi.jl, src/krylov_phiv_adaptive.jl, test/basictests.jl
Fixes #143 
I looked into that issue a bit more. Expokit.jl uses the same initial time step as ExponentialUtilities.jl, but does not face the dimension-1 issue since it stops timestepping upon a happy breakdown. When using the matrix dimension as the Krylov subspace dimension,  happy breakdown will occur and there is no need for taking (potentially very small) time steps.
=> Finish timestepping after happy breakdown

src/krylov_phiv.jl, src/krylov_phiv_error_estimate.jl
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
Currently, krylov_phiv_error_estimate.jl only implements the Lanczos algorithm for Hermitian matrix, which gives a tridiagonal H to use with the expT! functiopns's stegr call
https://github.com/SciML/ExponentialUtilities.jl/blob/18e5161ad28e49e2b92c5f4879495dbd55a0b52e/src/krylov_phiv_error_estimate.jl#L29
This PR passes on the `ishermitian` argument and errors if false.
Fixes #160
--
whitespace changes is with JuliaFormatter's sciml style.
=> expv error estimate: hermitian only

src/exp.jl
This PR changes the docstring for the `exponential!` function so that the example is runnable. Fixes #131.
=> fix exponential! example

.github/workflows/FormatCheck.yml, src/krylov_phiv_adaptive.jl
Use organisation wide formatting workflow.
=> ci: use reusable formatting workflow

src/exp_generic.jl
I'm in general pretty skeptical of the `naivemul` introduced in https://github.com/SciML/ExponentialUtilities.jl/pull/57, but this at least makes it dramatically better for sparse matrices. This improves, but does not fix https://github.com/SciML/OrdinaryDiffEq.jl/issues/2121.
```
julia> @time exponential!(sprand(500,500,.001), ExpMethodGeneric());
9.914123 seconds (52 allocations: 13.983 MiB)
#after
@time exponential!(sprand(500,500,.001), ExpMethodGeneric());
2.100566 seconds (260 allocations: 14.785 MiB)
```
=> don't use generated function implimentation of naivemul for sparse matrices

.gitignore, Project.toml, ext/ExponentialUtilitiesStaticArraysExt.jl, src/krylov_phiv.jl, src/phi.jl, test/basictests.jl
- Added ext/ExponentialUtilitiesStaticArraysExt.jl, which computes the exponential matrix-vector product efficiently when using StaticArrays.
- Updated authors list, version #, and uuid in Project.toml.
- Changed `== nothing` and `=== nothing` to isnothing.
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
This implementation is based on the work by Al-Mohy, A. H., & Higham, N. J. titled "Computing the action of the matrix exponential, with an application to exponential integrators", published in 2011 in SIAM journal on scientific computing, 33(2), 488-511.
=> Added StaticArrays extension for expv method

src/arnoldi.jl
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
Allow for overriding the type of the basis vector matrix `V` used for the KrylovSubspace. `V` has to be a GPUArray if  `arnoldi!(Ks,A,b)` is executed for `b` being GPUArray.
=> Parametrize VType in KrylovSubspace constructor
